apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-service
  template:
    metadata:
      labels:
        app: pokemon-service
    spec:
      containers:
        - name: pokemon-service
          image: pokemon-service:latest
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
                  name: common-config
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: pokemon-service-config
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_SERVICE_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
            - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
                  name: pokemon-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-service
spec:
  selector:
    app: pokemon-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pokemon-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/pokemon"